UI option for 'Thread Count' is enabled in EO Properties dialog. Code generation changes for 'needSerialization' field in EoConfig structure. Migration changes for old models.
Changes in the build logger to verify compilation error.


git-svn-id: http://clovisforge.openclovis.org:8888/svn/clasp/branches/5.0@5544 8a546835-ab24-0410-9070-dd6b907a2c58